#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xam.MapMyIndia.Droid.Resource", IsApplication=false)]

namespace Xam.MapMyIndia.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public static int mapbox_apiBaseUrl = 2130771977;
			
			// aapt resource value: 0x7f010007
			public static int mapbox_bl_arrowDirection = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int mapbox_bl_arrowHeight = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int mapbox_bl_arrowPosition = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int mapbox_bl_arrowWidth = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int mapbox_bl_bubbleColor = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int mapbox_bl_cornersRadius = 2130771969;
			
			// aapt resource value: 0x7f010006
			public static int mapbox_bl_strokeColor = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int mapbox_bl_strokeWidth = 2130771973;
			
			// aapt resource value: 0x7f01000e
			public static int mapbox_cameraBearing = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public static int mapbox_cameraTargetLat = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int mapbox_cameraTargetLng = 2130771980;
			
			// aapt resource value: 0x7f01000f
			public static int mapbox_cameraTilt = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public static int mapbox_cameraZoom = 2130771981;
			
			// aapt resource value: 0x7f010010
			public static int mapbox_cameraZoomMax = 2130771984;
			
			// aapt resource value: 0x7f010011
			public static int mapbox_cameraZoomMin = 2130771985;
			
			// aapt resource value: 0x7f01002f
			public static int mapbox_enableTilePrefetch = 2130772015;
			
			// aapt resource value: 0x7f010030
			public static int mapbox_enableZMediaOverlay = 2130772016;
			
			// aapt resource value: 0x7f01000a
			public static int mapbox_localIdeographFontFamily = 2130771978;
			
			// aapt resource value: 0x7f010031
			public static int mapbox_pixelRatio = 2130772017;
			
			// aapt resource value: 0x7f01002d
			public static int mapbox_renderTextureMode = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public static int mapbox_renderTextureTranslucentSurface = 2130772014;
			
			// aapt resource value: 0x7f010008
			public static int mapbox_styleUrl = 2130771976;
			
			// aapt resource value: 0x7f010026
			public static int mapbox_uiAttribution = 2130772006;
			
			// aapt resource value: 0x7f010027
			public static int mapbox_uiAttributionGravity = 2130772007;
			
			// aapt resource value: 0x7f01002b
			public static int mapbox_uiAttributionMarginBottom = 2130772011;
			
			// aapt resource value: 0x7f010028
			public static int mapbox_uiAttributionMarginLeft = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public static int mapbox_uiAttributionMarginRight = 2130772010;
			
			// aapt resource value: 0x7f010029
			public static int mapbox_uiAttributionMarginTop = 2130772009;
			
			// aapt resource value: 0x7f01002c
			public static int mapbox_uiAttributionTintColor = 2130772012;
			
			// aapt resource value: 0x7f010018
			public static int mapbox_uiCompass = 2130771992;
			
			// aapt resource value: 0x7f01001f
			public static int mapbox_uiCompassDrawable = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public static int mapbox_uiCompassFadeFacingNorth = 2130771998;
			
			// aapt resource value: 0x7f010019
			public static int mapbox_uiCompassGravity = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public static int mapbox_uiCompassMarginBottom = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public static int mapbox_uiCompassMarginLeft = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public static int mapbox_uiCompassMarginRight = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public static int mapbox_uiCompassMarginTop = 2130771995;
			
			// aapt resource value: 0x7f010016
			public static int mapbox_uiDoubleTapGestures = 2130771990;
			
			// aapt resource value: 0x7f010020
			public static int mapbox_uiLogo = 2130772000;
			
			// aapt resource value: 0x7f010021
			public static int mapbox_uiLogoGravity = 2130772001;
			
			// aapt resource value: 0x7f010025
			public static int mapbox_uiLogoMarginBottom = 2130772005;
			
			// aapt resource value: 0x7f010022
			public static int mapbox_uiLogoMarginLeft = 2130772002;
			
			// aapt resource value: 0x7f010024
			public static int mapbox_uiLogoMarginRight = 2130772004;
			
			// aapt resource value: 0x7f010023
			public static int mapbox_uiLogoMarginTop = 2130772003;
			
			// aapt resource value: 0x7f010014
			public static int mapbox_uiRotateGestures = 2130771988;
			
			// aapt resource value: 0x7f010013
			public static int mapbox_uiScrollGestures = 2130771987;
			
			// aapt resource value: 0x7f010015
			public static int mapbox_uiTiltGestures = 2130771989;
			
			// aapt resource value: 0x7f010017
			public static int mapbox_uiZoomControls = 2130771991;
			
			// aapt resource value: 0x7f010012
			public static int mapbox_uiZoomGestures = 2130771986;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int mapbox_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int mapbox_gray = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int mapbox_gray_dark = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int mapbox_eight_dp = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int mapbox_four_dp = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int mapbox_infowindow_margin = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int mapbox_infowindow_tipview_width = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int mapbox_minimum_angular_velocity = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int mapbox_minimum_scale_span_when_rotating = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int mapbox_minimum_scale_velocity = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int mapbox_my_locationview_outer_circle = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int mapbox_ninety_two_dp = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int mapbox_bhuwan_logo_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int mapbox_compass_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int mapbox_info_bg_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int mapbox_info_icon_default = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int mapbox_info_icon_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int mapbox_infowindow_icon_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int mapbox_logo_helmet = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int mapbox_logo_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int mapbox_mapmyindia_logo_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int mapbox_marker_icon_default = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int mapbox_markerview_icon_default = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int mapbox_mylocation_bg_shape = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int mapbox_mylocation_icon_bearing = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int mapbox_mylocation_icon_default = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int mapbox_popup_window_transparent = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int mapbox_rounded_corner = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public static int attributionView = 2131165203;
			
			// aapt resource value: 0x7f070000
			public static int bottom = 2131165184;
			
			// aapt resource value: 0x7f070004
			public static int center = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int center_horizontal = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int center_vertical = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int clip_horizontal = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int clip_vertical = 2131165192;
			
			// aapt resource value: 0x7f070011
			public static int compassView = 2131165201;
			
			// aapt resource value: 0x7f070009
			public static int end = 2131165193;
			
			// aapt resource value: 0x7f070017
			public static int error_text_view = 2131165207;
			
			// aapt resource value: 0x7f07000a
			public static int fill = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int fill_horizontal = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public static int fill_vertical = 2131165196;
			
			// aapt resource value: 0x7f070019
			public static int image = 2131165209;
			
			// aapt resource value: 0x7f07000f
			public static int infowindow_description = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public static int infowindow_title = 2131165198;
			
			// aapt resource value: 0x7f070001
			public static int left = 2131165185;
			
			// aapt resource value: 0x7f070015
			public static int loading_map_text_view = 2131165205;
			
			// aapt resource value: 0x7f070012
			public static int logoView = 2131165202;
			
			// aapt resource value: 0x7f07001a
			public static int mapView = 2131165210;
			
			// aapt resource value: 0x7f070016
			public static int map_loading_issue_layout = 2131165206;
			
			// aapt resource value: 0x7f070018
			public static int map_retry_button = 2131165208;
			
			// aapt resource value: 0x7f070010
			public static int markerViewContainer = 2131165200;
			
			// aapt resource value: 0x7f070002
			public static int right = 2131165186;
			
			// aapt resource value: 0x7f070014
			public static int splash_view = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public static int start = 2131165197;
			
			// aapt resource value: 0x7f070003
			public static int top = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int mapbox_attribution_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int mapbox_infowindow_content = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int mapbox_mapview_internal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int mapbox_view_image_marker = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int MMIMapLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060019
			public static int library_name = 2131099673;
			
			// aapt resource value: 0x7f060000
			public static int mapbox_attributionErrorNoBrowser = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int mapbox_attributionTelemetryMessage = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int mapbox_attributionTelemetryNegative = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int mapbox_attributionTelemetryNeutral = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int mapbox_attributionTelemetryPositive = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int mapbox_attributionTelemetryTitle = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int mapbox_attributionsDialogTitle = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int mapbox_attributionsIconContentDescription = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int mapbox_compassContentDescription = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int mapbox_loading_map = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int mapbox_mapActionDescription = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public static int mapbox_myLocationViewContentDescription = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public static int mapbox_offline_error_region_definition_invalid = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public static int mapbox_retry = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public static int mapbox_something_went_wrong_map_loading = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public static int mapbox_style_dark = 2131099663;
			
			// aapt resource value: 0x7f060010
			public static int mapbox_style_light = 2131099664;
			
			// aapt resource value: 0x7f060011
			public static int mapbox_style_mapbox_streets = 2131099665;
			
			// aapt resource value: 0x7f060012
			public static int mapbox_style_outdoors = 2131099666;
			
			// aapt resource value: 0x7f060013
			public static int mapbox_style_satellite = 2131099667;
			
			// aapt resource value: 0x7f060014
			public static int mapbox_style_satellite_streets = 2131099668;
			
			// aapt resource value: 0x7f060015
			public static int mapbox_style_traffic_day = 2131099669;
			
			// aapt resource value: 0x7f060016
			public static int mapbox_style_traffic_night = 2131099670;
			
			// aapt resource value: 0x7f060017
			public static int mapbox_telemetryLink = 2131099671;
			
			// aapt resource value: 0x7f060018
			public static int mapbox_telemetrySettings = 2131099672;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] mapbox_BubbleLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 7
			public static int mapbox_BubbleLayout_mapbox_bl_arrowDirection = 7;
			
			// aapt resource value: 2
			public static int mapbox_BubbleLayout_mapbox_bl_arrowHeight = 2;
			
			// aapt resource value: 3
			public static int mapbox_BubbleLayout_mapbox_bl_arrowPosition = 3;
			
			// aapt resource value: 0
			public static int mapbox_BubbleLayout_mapbox_bl_arrowWidth = 0;
			
			// aapt resource value: 4
			public static int mapbox_BubbleLayout_mapbox_bl_bubbleColor = 4;
			
			// aapt resource value: 1
			public static int mapbox_BubbleLayout_mapbox_bl_cornersRadius = 1;
			
			// aapt resource value: 6
			public static int mapbox_BubbleLayout_mapbox_bl_strokeColor = 6;
			
			// aapt resource value: 5
			public static int mapbox_BubbleLayout_mapbox_bl_strokeWidth = 5;
			
			public static int[] mapbox_MapView = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017};
			
			// aapt resource value: 1
			public static int mapbox_MapView_mapbox_apiBaseUrl = 1;
			
			// aapt resource value: 6
			public static int mapbox_MapView_mapbox_cameraBearing = 6;
			
			// aapt resource value: 3
			public static int mapbox_MapView_mapbox_cameraTargetLat = 3;
			
			// aapt resource value: 4
			public static int mapbox_MapView_mapbox_cameraTargetLng = 4;
			
			// aapt resource value: 7
			public static int mapbox_MapView_mapbox_cameraTilt = 7;
			
			// aapt resource value: 5
			public static int mapbox_MapView_mapbox_cameraZoom = 5;
			
			// aapt resource value: 8
			public static int mapbox_MapView_mapbox_cameraZoomMax = 8;
			
			// aapt resource value: 9
			public static int mapbox_MapView_mapbox_cameraZoomMin = 9;
			
			// aapt resource value: 39
			public static int mapbox_MapView_mapbox_enableTilePrefetch = 39;
			
			// aapt resource value: 40
			public static int mapbox_MapView_mapbox_enableZMediaOverlay = 40;
			
			// aapt resource value: 2
			public static int mapbox_MapView_mapbox_localIdeographFontFamily = 2;
			
			// aapt resource value: 41
			public static int mapbox_MapView_mapbox_pixelRatio = 41;
			
			// aapt resource value: 37
			public static int mapbox_MapView_mapbox_renderTextureMode = 37;
			
			// aapt resource value: 38
			public static int mapbox_MapView_mapbox_renderTextureTranslucentSurface = 38;
			
			// aapt resource value: 0
			public static int mapbox_MapView_mapbox_styleUrl = 0;
			
			// aapt resource value: 30
			public static int mapbox_MapView_mapbox_uiAttribution = 30;
			
			// aapt resource value: 31
			public static int mapbox_MapView_mapbox_uiAttributionGravity = 31;
			
			// aapt resource value: 35
			public static int mapbox_MapView_mapbox_uiAttributionMarginBottom = 35;
			
			// aapt resource value: 32
			public static int mapbox_MapView_mapbox_uiAttributionMarginLeft = 32;
			
			// aapt resource value: 34
			public static int mapbox_MapView_mapbox_uiAttributionMarginRight = 34;
			
			// aapt resource value: 33
			public static int mapbox_MapView_mapbox_uiAttributionMarginTop = 33;
			
			// aapt resource value: 36
			public static int mapbox_MapView_mapbox_uiAttributionTintColor = 36;
			
			// aapt resource value: 16
			public static int mapbox_MapView_mapbox_uiCompass = 16;
			
			// aapt resource value: 23
			public static int mapbox_MapView_mapbox_uiCompassDrawable = 23;
			
			// aapt resource value: 22
			public static int mapbox_MapView_mapbox_uiCompassFadeFacingNorth = 22;
			
			// aapt resource value: 17
			public static int mapbox_MapView_mapbox_uiCompassGravity = 17;
			
			// aapt resource value: 21
			public static int mapbox_MapView_mapbox_uiCompassMarginBottom = 21;
			
			// aapt resource value: 18
			public static int mapbox_MapView_mapbox_uiCompassMarginLeft = 18;
			
			// aapt resource value: 20
			public static int mapbox_MapView_mapbox_uiCompassMarginRight = 20;
			
			// aapt resource value: 19
			public static int mapbox_MapView_mapbox_uiCompassMarginTop = 19;
			
			// aapt resource value: 14
			public static int mapbox_MapView_mapbox_uiDoubleTapGestures = 14;
			
			// aapt resource value: 24
			public static int mapbox_MapView_mapbox_uiLogo = 24;
			
			// aapt resource value: 25
			public static int mapbox_MapView_mapbox_uiLogoGravity = 25;
			
			// aapt resource value: 29
			public static int mapbox_MapView_mapbox_uiLogoMarginBottom = 29;
			
			// aapt resource value: 26
			public static int mapbox_MapView_mapbox_uiLogoMarginLeft = 26;
			
			// aapt resource value: 28
			public static int mapbox_MapView_mapbox_uiLogoMarginRight = 28;
			
			// aapt resource value: 27
			public static int mapbox_MapView_mapbox_uiLogoMarginTop = 27;
			
			// aapt resource value: 12
			public static int mapbox_MapView_mapbox_uiRotateGestures = 12;
			
			// aapt resource value: 11
			public static int mapbox_MapView_mapbox_uiScrollGestures = 11;
			
			// aapt resource value: 13
			public static int mapbox_MapView_mapbox_uiTiltGestures = 13;
			
			// aapt resource value: 15
			public static int mapbox_MapView_mapbox_uiZoomControls = 15;
			
			// aapt resource value: 10
			public static int mapbox_MapView_mapbox_uiZoomGestures = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
